install ath12k_wifi6 /bin/sh -c '\
board_name=$(cat /tmp/sysinfo/board_name 2>/dev/null); \
if [[ "$board_name" == *ap-al02-c13* ]]; then \
    /sbin/modprobe --ignore-install ath12k_wifi6 $CMDLINE_OPTS; \
fi'
